Repository Psychedelic/plug, pull requests merged in 2021-09, with the labels that each got.

#221 Default account emoji on creation
  package.json
  source/Options/Views/Welcome/steps/CreatePasswordStep.jsx
  source/Popup/Views/ExportIdentity/steps/Step2.jsx
  source/components/Profile/index.jsx
  source/components/UserIcon/index.jsx
  source/components/UserIcon/styles.js
  yarn.lock
Labels: bug, enhancement

#225 Fix/icp price refactor
  .gitignore
  source/Background/Keyring.js
  source/Pages/Notification/components/Transfer/components/Details.jsx
  source/Pages/Notification/components/Transfer/index.jsx
  source/Popup/Views/AddToken/Steps/Step2.jsx
  source/Popup/Views/Home/index.jsx
  source/Popup/Views/Send/Steps/Step3/index.jsx
  source/Popup/Views/Send/hooks/useSteps.jsx
  source/components/Activity/index.jsx
  source/components/Profile/index.jsx
  source/components/Tokens/index.jsx
  source/redux/icp.js
  source/redux/wallet.js
  source/shared/constants/currencies.js
Labels: enhancement

#229 Webextension polyfill replaced by extensionizer
  package.json
  source/Popup/Views/AddToken/components/CustomToken.jsx
  source/Popup/Views/AddToken/components/DabComingSoon.jsx
  source/Popup/Views/Deposit/Steps/Step2.jsx
  source/Popup/Views/Login/index.jsx
  source/Popup/Views/NFTDetails/index.jsx
  source/Popup/Views/Send/Steps/Step3/index.jsx
  source/Popup/Views/WalletDetails/index.jsx
  source/Popup/index.jsx
  source/ui/ActivityItem/index.jsx
  source/ui/WhitelistItem/index.jsx
  webpack.config.js
  webpack.inpage.js
  yarn.lock
Labels: enhancement, invalid

#232 Feature/dab canisters info
  .gitignore
  package.json
  source/Background/Controller.js
  source/Background/index.js
  source/Pages/Notification/components/AllowAgent/index.jsx
  source/Pages/Notification/components/AllowAgent/styles.js
  source/Pages/Notification/components/AppConnection/index.jsx
  source/Pages/Notification/components/AppConnection/styles.js
  source/Popup/Views/Send/Steps/Step3/index.jsx
  source/components/Apps/index.jsx
  source/components/Apps/styles.js
  source/locales/en/translation.json
  source/shared/constants/urls.js
  source/ui/ActivityItem/index.jsx
  source/ui/CanisterInfo/components/Container/index.jsx
  source/ui/CanisterInfo/components/Container/styles.js
  source/ui/CanisterInfo/components/Item/index.jsx
  source/ui/CanisterInfo/components/Item/styles.js
  source/ui/Container/index.jsx
  source/ui/IncomingAction/styles.js
  source/ui/WhitelistContainer/index.jsx
  source/ui/WhitelistItem/index.jsx
  source/ui/WhitelistItem/styles.js
  source/ui/index.js
  yarn.lock
Labels: bug, enhancement, help wanted

#236 Canister info fallback
  source/Background/Controller.js
Labels: bug
